.gitignore, README.md, cernbox-wopi-server.spec, docker/Dockerfile, docker/buildimage.sh, docker/scripts/entrypoint, docker/wopiserver.conf, src/wopiserver.py, src/xrootiface.py, wopiserver.conf
This is a 'clone' of Michael's PR but targeting a different branch on the CERNBox repository, in order to work out the details and leave the merge to master for when the changes are all tested in the CERN environment.
=> Make code more generic + docker image fixes for AARNet

requirements.txt, src/cs3iface.py, src/wopiutils.py
First try to connect the wopi server with Reva. We still need to figure out authentication and clean up the code.
=> WIP Connect wopi reva

src/cs3iface.py
The write file method is still not working and there are cleanups to be done.
=> WIP Connect reva with wopi

cernbox-wopi-server.spec, docker/buildimage_wopiserver.sh, src/cs3iface.py, src/wopiserver.py
This removes a redundant id, keeping both will result in errors (but no error msg) in reva.
=> Fix read file

cernbox-wopi-server.spec, src/wopiserver.py
=> Remove merge conflicts

src/cs3iface.py
https://cs3org.github.io/cs3apis/#cs3.storage.provider.v1beta1.Reference
=> Remove TODO

src/wopiserver.py, test/wopi-validator.md, tools/wopiopen.py
Instructions and docker image kindly provided by Thomas/ownCloud. Yet to be tested.
The wopiopen tool has been extended to support the validator accordingly.
=> Added instructions to run the WOPI validator test

src/xrootiface.py, test/test_storageiface.py
Cf. https://its.cern.ch/jira/browse/CERNBOX-1216. This is a clone in python of the code around:
https://github.com/cernbox/revaold/blob/master/api/public_link_manager_owncloud/public_link_manager_owncloud.go#L127
Also added a test case for this feature.
=> Implement perma-inode statx for xrootd/eos

README.md
Update the documentation for needed reva configs.
=> Update config doc

.drone.yml
Following the schema introduced on the Makefile in 4d6fb0216845e6148aea290074b5ee56b098e922
=> CI: Add VERSION build-arg to both release pipelines

src/wopiserver.py
This fixes cases of documents in OnlyOffice that keep a docid, coming from this `lockid`, that is never refreshed if the user for some reason never closed the document, whereas the session is made to expire after 24h typically.
=> The lockid returned by /cbox/lock must be newer than the token expiration time

src/bridge/__init__.py, src/wopiserver.py
Following cs3org/reva#1923, this PR provides the needed JSON encoding for the Reva AppProvider's wopi driver when using the `/wopi/iop/openinapp` endpoint.
The old `/wopi/cbox/open` is still backward compatible, and error handling has been unified such that:
* On success, `/openinapp` returns a JSON and `/open` returns the URL payload as before
* On errors, they both return an error string and an HTTP status code
The `/wopi/bridge/open` endpoint used by the old Reva for CodiMD also works similarly.
=> New model for the openinapp endpoint

src/wopiserver.py
fixes https://github.com/cs3org/reva/pull/1968?#issuecomment-898253543
=> make appviewurl default to appurl

README.md, src/core/wopi.py, src/core/wopiutils.py
=> Updated contributors

src/core/cs3iface.py, src/core/localiface.py, src/core/wopi.py, src/core/wopiutils.py, src/core/xrootiface.py, test/test_storageiface.py
=> Use etags as WOPI versions

src/core/wopi.py, src/core/wopiutils.py, src/wopiserver.py, wopiserver.conf
For the moment, this only adds logic and logging to validate whether
the heuristic is correct, without taking any action.
=> Refactor logs around returning HTTP 409 responses to better understand MS Office 365 behavior

wopiserver.Dockerfile
```sh
❯ trivy image cs3org/wopiserver:latest
2022-09-30T14:04:12.004+0200	INFO	Vulnerability scanning is enabled
2022-09-30T14:04:12.004+0200	INFO	Secret scanning is enabled
2022-09-30T14:04:12.004+0200	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-09-30T14:04:12.004+0200	INFO	Please see also https://aquasecurity.github.io/trivy/v0.32/docs/secret/scanning/#recommendation for faster secret detection
2022-09-30T14:07:21.688+0200	INFO	Detected OS: debian
2022-09-30T14:07:21.688+0200	INFO	Detecting Debian vulnerabilities...
2022-09-30T14:07:21.802+0200	INFO	Number of language-specific files: 1
2022-09-30T14:07:21.803+0200	INFO	Detecting python-pkg vulnerabilities...
cs3org/wopiserver:latest (debian 11.5)
Total: 1176 (UNKNOWN: 0, LOW: 600, …
```
=> Use python-alpine docker base image

requirements.txt, src/bridge/wopiclient.py, src/core/commoniface.py, src/core/cs3iface.py, src/core/localiface.py, src/core/wopi.py, src/core/xrootiface.py, test/test_storageiface.py
Following up https://github.com/cs3org/cs3apis/pull/183
Closes #86.
=> Reimplement UnlockAndRelock

docker/etc/wopiserver.conf, src/wopiserver.py, wopiserver.conf
Fixes: https://github.com/cs3org/wopiserver/issues/83
=> feat: add option to use file or stream handler for logging

src/core/wopi.py
This mini PR disables the capability to execute `PutRelative` (aka "Save As") when the user is not owner of the file.
The rationale is that on single-file shares this operation is bound to fail with permission denied, and even in folder shares the UX may not be great (as owner I may not like that collaborators rename or save copies of my files). Given that we don't have for now a mechanism to tell apart single-file shares from all the rest, this approach seems the safest.
=> Disable SaveAs when user is not owner

src/core/wopi.py, src/core/wopiutils.py
This pull request  aims to enhance error handling in our codebase by enforcing the consistent usage of JSON throughout the API.
Fixes: #96
=> chore: Ensure consistent use of JSON and add standard response headers

src/core/wopi.py
=> GetFile: URL-encode filename to try and avoid Unicode issues

src/bridge/codimd.py, src/bridge/etherpad.py, src/bridge/wopiclient.py, src/core/cs3iface.py, src/core/localiface.py, src/core/xrootiface.py
Linting: all exceptions are re-raised from the original ones.
HTTP requests hardening: all requests include a timeout and exception handling takes it into account.
=> Linting and hardening HTTP requests
