.drone.yml

Create `release` & `release-latest` pipelines so we can push and use images from https://hub.docker.com/r/cs3org/wopiserver 
@glpatcern could you give a smoke test to the _freshly-baked_ `cs3org/wopiserver:latest` image to see if it built properly on my fork's [drone](https://cloud.drone.io/SamuAlfageme/wopiserver/3/1/2)? 
This closes https://github.com/sciencemesh/sciencemesh/issues/63

Enable Drone CI builds for tags and latest (master)

---

src/cs3iface.py

Here we use PUT instead of the tus client, this is because we get a 501 return when using tus. I think we should use tus in the future. Tus needs to be disabled in reva for local fs for this to work.

WIP: Fix write file

---

cernbox-wopi-server.spec
src/wopiserver.py

As agreed with @diocas, with this PR we return the lock initial creation timestamp on `/wopi/cbox/lock` (both on POST and on GET).
This is to meet the OnlyOffice requirement that "Every time the document is edited and saved, the key must be generated anew", but the document's key must persist any intermediate save operation. Therefore, the key's lifetime exactly matches the interop/wopi lock lifetime.

Interop locking enhancements for OnlyOffice

---

cernbox-wopi-server.spec
src/wopiserver.py
src/wopiutils.py
test/wopiserver-test.conf
tools/wopilistopenfiles.sh
tools/wopiopen.py
wopiserver.conf

To match https://github.com/cs3org/cs3apis/pull/75, this implements a new `/wopi/iop/open` endpoint with the following arguments:
Required headers:
- `Authorization: Bearer` and the shared Reva/WOPI secret
- `TokenHeader`: an x-access-token to serve as user identity towards Reva
Query parameters:
- string viewmode: how the user should access the file - one of `VIEW_MODE_VIEW_ONLY`, `VIEW_MODE_READ_ONLY`, `VIEW_MODE_READ_WRITE`, defaults to `VIEW_MODE_READ_ONLY`
- string username (optional): user's full display name, typically shown by the Office app
- string filename OR fileid: the full path of the filename to be opened, or its fileid
- string folderurl: the URL to come back to the containing folder for this file, typically shown by the Office app
- string endpoint (optional): the storage …

Provide a `/wopi/iop/open` endpoint

---

README.md
src/cs3iface.py
test/test_storageiface.py
test/wopiserver-test.conf
wopiserver.conf

This PR makes uploads work with tus and uploads and downloads through the reva data gateway. Reva also provides the option to configure storage mount paths, which is now also handled.
With the default [ocmd-server-1.toml](https://github.com/cs3org/reva/blob/master/examples/ocmd/ocmd-server-1.toml) config,
```
WOPI_STORAGE=cs3 python3 test_storageiface.py
...........
----------------------------------------------------------------------
Ran 11 tests in 0.389s
OK
```
There was one bug with both tus and gateway enabled, which will be fixed by [this](https://github.com/cs3org/reva/pull/1082/files#diff-ad6752b68b3f98ff0057741434896a36R67).

Make uploads work with tus and through gateway

---

cernbox-wopi-server.spec
src/cs3iface.py
src/localiface.py
src/wopiserver.py
src/wopiutils.py
src/xrootiface.py
test/test_storageiface.py
test/wopiserver-test.conf

This is to better support lock operations in the `/wopi/cbox/lock` and `/wopi/cbox/unlock` WOPI extensions.
Work to do:

Add support for atomic locking

---

src/cs3iface.py

With latest master of the WOPI server I get following error. My fix only works with latest REVA. Changes were introduced in https://github.com/cs3org/cs3apis/pull/130
```
wopiserver_1       | {"time": "2021-06-23T08:46:25", "host": "8463d56ab59d", "process": "WOPIServer", "level": "ERROR", msg="Unexpected exception caught" exception="Protocol message Reference has no "id" field." type="<class 'ValueError'>" traceback="['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.8/site-packages/prometheus_flask_exporter/__init__.py", line 639, in func\n    response = f(*args, **kwargs)\n', '  File "/app/wopiserver.py", line 309, in iopOpen\n    inode, acctok = utils.generateAccessToken(userid, fileid, viewmode, username, folderurl, endpoint)\n', '  File "/app/wopiutils.py", …
```

Adapt to new CS3API Reference

---

src/core/wopi.py

This mini PR changes the filename pattern used to generate conflict files, in the case when a file is requested to be overwritten (via WOPI PutFile) but it had changed in the storage via other requests (e.g. sync client).
The motivation is to limit the proliferation of such conflict files: the user may not immediately realize a conflict was generated (often because the save operations happen asynchronously) and keeps using the application, therefore ending up with several conflict files where only the last one is relevant.
The new pattern uses just the hour as opposed to hour-minute-second.

Limit conflict files to one per hour

---

requirements.txt
src/wopiserver.py
wopiserver.conf

To enable the waitress server for production setups, set the new config option `internalserver` to `waitress`.
See https://dev.to/thetrebelcc/how-to-run-a-flask-app-over-https-using-waitress-and-nginx-2020-235c
for explanation.

Use waitress http server for production deployments.

---

wopiserver.logrotate

using "restart" on logrotate files is never an appropiate action
as the service should only be restarted if it was actually running
before logrotate started.

logrotate: Use reload-or-try-restart instead.

---

README.md
requirements.txt
src/bridge/__init__.py
src/bridge/codimd.py
src/bridge/etherpad.py
src/bridge/wopiclient.py
src/core/commoniface.py
src/core/cs3iface.py
src/core/discovery.py
src/core/ioplocks.py
src/core/localiface.py
src/core/wopi.py
src/core/wopiutils.py
src/core/xrootiface.py
src/wopiserver.py
test/test_storageiface.py
test/wopi-validator.md
test/wopiserver-test.conf
wopiserver.Dockerfile
wopiserver.conf
wopiserver.yaml

This PR introduces a lock API in the storage interfaces and uses it throughout the WOPI logic instead of directly creating lock files.
The lock API is implemented in the xrootd and local interfaces. ~Once https://github.com/cs3org/cs3apis/pull/160 is merged and implemented in Reva, the cs3iface will also be implemented.~ Edit: this was tested in CERNBox QA.
Along with this enhancement, all cases of failures or permission issues when saving a file have been identified and an attempt is made to save a copy to a configured local storage in order to ease later recovery by service operations.
The same process is performed by the bridge extension: this fixes https://github.com/cs3org/wopiserver/issues/39.
Highlights of the implementation:
* Lock operations are now clearly separated in the WOPI …

New feature: implement locking via Lock API

---

src/core/commoniface.py
src/core/localiface.py
src/core/wopiutils.py
src/core/xrootiface.py
test/test_storageiface.py
test/wopiserver-test.conf

In this PR some lock handling logic has been removed from the core WOPI logic and delegated to the storage interfaces, in the assumption that the different CS3 storage providers do implement what is required:
* `getlock()` of an expired lock returns `None`
* `refreshlock()` and `setlock()` of an existing or expired lock behave as per CS3API specs
* A lock is not any longer auto-extended based on the last save time from `PutFile` actions.
The xrootd interface has been adapted, but the detection of external locks now depends on the (EOS) storage to fail a `setlock()` operation when a `flock` exists on the file, as the wopiserver cannot tell any longer if a previously found LibreOffice lock is not owned by itself in the general case of no permissions in the folder (single-file share). Yet, …

Push lock handling logic to storage interfaces

---

src/core/wopi.py

One can disable the creation of file based locks by a feature flag. In the unlock method, the file based lock was still removed (and failed gracefully) even if file based locking was disabled.

skip file based locking check if disabled by feature flag

---

src/core/cs3iface.py

this is about this code path: https://github.com/cs3org/reva/blob/208ecee6d113e2b323c80e366a92eedb776200f9/pkg/storage/utils/decomposedfs/node/node.go#L512-L520
If we omit the `path='.'` we'll get a stat response containing the absolute path of the file (not the filename only)

use a relative reference for the stat request in the cs3 api

---

src/core/wopi.py
src/core/wopiutils.py

This refactoring improves the handling of conflict when external locks are found, such that in all cases an attempt is made to create a `<filename>-webconflict-<timestamp>` file in some user-accessible space.

Refactored PutFile logic

---

README.md
requirements.txt
src/core/cs3iface.py

We now optionally split the space id from the endpoint. This keeps the wopiserver compatible with reva master and reva edge, where we add the space id with: https://github.com/cs3org/reva/pull/3074

Optionally split space from endpoint

---

src/bridge/__init__.py
src/bridge/codimd.py
src/bridge/etherpad.py
src/bridge/wopiclient.py
src/core/commoniface.py
src/core/localiface.py
src/core/wopi.py
src/wopiserver.py

This PR refactors the bridge logic around save and relock operations, as the application is now inferred from the remote IP contacting the save endpoint. This also ensures no unregistered app can interfere with the save workflow, and allows simplifying the lock structure.
At the same time, the `/wopi/bridge/open` endpoint has been removed as it was already deprecated and only used by the old CERNBox UI, which is progressively being replaced by the new OCIS/Reva infrastructure.

Bridge: validate app by source IP and simplify lock structure

---

src/bridge/__init__.py
src/bridge/codimd.py
src/bridge/etherpad.py
src/bridge/readme.md

This PR includes a minimal complete implementation to support Etherpad. It also includes a change to pass and get `WOPISrc` and `access_token` as separate parameters on the `/wopi/bridge/<docid>` save endpoint, to allow for more flexibility on the apps side.

First implementation to support the save webhook in Etherpad

---

src/core/cs3iface.py
src/core/wopi.py
src/core/wopiutils.py

needed to improve #76 
```sh
./Microsoft.Office.WopiValidator -n SuccessfulLockSequence -w https://wopiserver.team.owncloud.works/wopi/files/<fileID> -t <token> -l 1663776371000
Test group: Locks
Pass: SuccessfulLockSequence
```

fix UnLockAndRelock and length of resourceIDs

---

src/wopiserver.py

Background: https://github.com/Pylons/waitress/issues/151
For `waitress` it's required to add a log handler to the root logger (which is recommended in general) otherwise `waitress` will add its own handler. As a result, there exists a waitress handler and a flask handler which are both used for logging.
Result with debug log level:
```Shell
❯ python3 src/wopiserver.py
{"time": "2022-10-11T11:18:20.548", "host": "superion", "level": "INFO", "process": "wopiserver", "module": "wopiserver", "msg": "WOPI Server starting in unsecure/embedded mode", "port": "8880", "wopiurl": "https://your-wopi-server.org:8443", "version": "git"}
{"time": "2022-10-11T11:18:25.721", "host": "superion", "level": "DEBUG", "process": "wopiserver", "module": "wopiserver", "msg": "Accessed index page", "client": …
```

fix duplicate logging entries

---

src/bridge/__init__.py
src/bridge/codimd.py
src/wopiserver.py

This PR adds the reva token to the data sent to the CodiMD client. This is temporary while another way to upload files is found, as discussed.

Send reva token to CodiMD

---

.github/workflows/python-app.yml
.gitignore
src/core/commoniface.py
src/core/cs3iface.py
src/core/localiface.py
src/core/wopi.py
src/core/wopiutils.py
src/core/xrootiface.py
test/test_storageiface.py
test/wopiserver-test.conf

Internal reference: https://its.cern.ch/jira/browse/CERNBOX-3016
Through validation tests, it turns out that rename operations (`MoveRequest` in CS3 API terms) ~~must be supported regardless if a file is locked~~ - edit: renames may still need a lock, regardless how Microsoft Office behaves. The test suite was amended to take that into account. Similarly, the wopiserver needs to be able to set an xattr on an unlocked file, but be denied if the file is locked and the lock does not match. This was incorporated as well in the test suite.
Validation tests:
~~- [ ] cs3 interface~~
~~- [ ] MS WOPI validator tests on top of cs3~~
Update: as renames were not changed, and as right now the CS3 interface on top of Reva `master` does not pass all the tests, we're not executing those tests. In a …

Implementation of EOS-supported locking

---

src/core/wopi.py
src/wopiserver.py
wopiserver.conf

This is actually a variant that supersedes https://github.com/cs3org/wopiserver/pull/102
The goal is to make the business flow dependent on the config flag only, not on whether the app is proxied or not, and to leave it out on public shares.
(And I gave up in hiding the technical details from the main `wopiserver.py` class)

Added configuration flag to enable the business flow

---

src/core/commoniface.py
src/core/wopi.py
src/core/wopiutils.py
src/core/xrootiface.py
src/wopiserver.py
wopiserver.conf

This PR introduces a feature to compensate an issue with the Microsoft Office cloud. It should hopefully be reverted once the issue is fixed with MS support.
The issue concerns a mishandling of collaborative sessions: it may happen that a new user trying to join an editing session is prevented from doing so because the existing session appears to be "forgotten" by the Microsoft cloud, whilst it is continuously being refreshed (therefore holding a valid WOPI lock). Typically this is the case when the existing session is not actively used, that is there has been no recent `PutFile` operation.
Here we introduce a configuration parameter `evictlocktime` and an `evictlock` additional query parameter on `/wopi/iop/openinapp`: if `evictlock=1` on the open call AND the file was saved more than …

Implemented forced eviction of locks

---

src/core/cs3iface.py

This allows supporting storages (like eos) that are able to be addressed by full path more efficiently, whilst supporting the decomposedfs Reva storage driver where resolving the `parent_id` is always required to access a file by filename.

cs3iface: allow using absolute paths if the storage driver returns them

---

src/core/wopi.py
wopiserver.conf

This feature allows to run the wopiserver in a less "conservative" mode as detailed in the `wopiserver.conf` comments.
The `lastmodificationtime` xattr is still stored in all cases as it is actually used for a particular lock check implemented for CodiMD. But the validation on `PutFile` is skipped when the detection flag is set to false.

Added config flag to disable detection of external changes

---

requirements.txt
src/core/cs3iface.py
src/core/localiface.py
src/core/xrootiface.py
src/wopiserver.py

Inspired by recent deployment attempts, this PR introduces a health check that is executed on the "index" page of the server. The goal is to have a quick feedback whether the service is properly configured to talk to the underlying storage.

Added health check of all storages

---

docker/etc/wopiserver.cs3.conf
src/core/cs3iface.py
wopiserver.conf

This fixes #125. To be reviewed.

CS3: implement locks as xattrs

---

src/core/wopi.py
src/core/wopiutils.py
src/wopiserver.py

Fixes #64. The trace is logged once for each request as part of the `client context`.

Implemented support for X-Trace-Id header

---

README.md

This is just a minor typo correction for an issue I noticed in the readme.

docs: Correct typo in name of wopisecret file

---

src/core/wopi.py
src/wopiserver.py

This patch fixes the logic to allow SaveAs operations.
As the wopiserver does not know if a public share (where a file was opened) can be written to, that is it's a shared folder, the SaveAs operation is now offered _only_ if the user is authenticated, otherwise only a "Download a copy" is possible, unless the `VIEW_ONLY` mode was used. The previous optimistic approach can lead to files successfully written (on behalf of the owner) to the shared folder, but inaccessible by the user, that is asked to login after the SaveAs operation.
For authenticated users, the behavior remains unchanged: if the shared folder is writable, a SaveAs operation will write a file in the same folder. Otherwise, the file is stored in the user's home folder, identified via the `homepath` configuration variable …

Fixed SaveAs logic for non-authenticated users

---

src/core/cs3iface.py

fix: stream file contents in cs3iface/readfile

---

src/core/cs3iface.py

This PR changes the wopiserver to treat 0-byte uploads as finished after the `InitiateFileUploadRequest` already to match the behavior of reva edge. I suppose this might break compatibility with reva master so it'll likely need some discussion.
@glpatcern In reva edge we [changed the behavior](https://github.com/cs3org/reva/commit/c90c0b03bec0cce84eb778a116e921077f632a71) for 0-byte uploads so that they are finalized as part of the `InitiateFileUploadRequest` request already. This is analogous to [what tusd does](https://github.com/tus/tusd/blob/main/pkg/handler/unrouted_handler.go#L415-L422) in the TUS POST requests and fixes a [bug with 0-byte TUS uploads](https://github.com/owncloud/ocis/issues/8003) where uploads were not finalized because reva doesn't use the TUS POST handler and …

0-byte uploads are completed after the InitiateFileUploads call already

---

src/core/cs3iface.py
src/core/localiface.py
src/core/wopi.py
src/core/wopiutils.py
src/core/xrootiface.py
test/test_storageiface.py

Supersedes https://github.com/cs3org/wopiserver/pull/138.
We use the flask write stream to spare an in-memory buffer copy (the actual request is still processed in one go as it's a POST).
The `writefile()` signature was changed to accept either a `byte[]` buffer or a stream as content, and the size as an extra parameter (`-1` would mean that the function must compute it assuming content is a buffer).
To be tested for all interfaces:

Use Flask stream when writing data to storage

---

src/core/cs3iface.py
src/core/localiface.py
src/core/xrootiface.py
test/test_storageiface.py
test/wopiserver-test.conf

cs3: fixed lock and error handling on writefile

---

src/core/localiface.py

This PR is a fix for the following error:
File "/app/core/localiface.py", line 286, in writefile written += f.write(chunk, offset=o, size=len(chunk)) 
TypeError: BufferedWriter.write() takes no keyword arguments
that occurs when a file must be saved and the local storage type is used.

Fix "TypeError: BufferedWriter.write() takes no keyword arguments" error in localiface.py

---

CHANGELOG.md
README.md
requirements.txt
src/core/commoniface.py
src/core/cs3iface.py
src/core/localiface.py
src/core/wopi.py
src/core/wopiutils.py
src/core/xrootiface.py
test/test_storageiface.py

This PR is to introduce the https://github.com/cs3org/cs3-python-client library contributed by @rawe0.
As part of this, some refactoring and simplification has taken place:
* Simplified xattrs handling: dropped the need for an independent `getxattr()` API, as well as the caching recently introduced, as the xattrs are always queried next to a stat call.
* Removed `versioninv` flag on stat, assuming it's always version invariant. Only xroot was able to make a distinction.
* Standardized `readfile` that now raises an exception instead of `yield`ing it. Consequently dropped the `peek` logic.
* Standardized error messages.
@micbar a heads-up about a larger-than-usual change.
Remaining tasks:

Introduce the new cs3-python-client library

---

src/core/wopi.py
src/core/wopiutils.py

This PR forces read-only mode also for many legacy Office formats, on top of the already implemented ODF files.
The breadcrumb "decoration" is also removed as nowadays Microsoft Office 365 does not display it.

Force read-only mode for unsupported legacy Office formats

---

src/core/wopi.py
src/core/wopiutils.py
src/wopiserver.py
wopiserver.conf

This is to allow disabling `Export As...` in Collabora, until we can properly support it. Supersedes #177

Introduce apps config section and option for Collabora
